2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_setup.py:_flush():67] Current SDK version is 0.19.7
2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_setup.py:_flush():67] Configure stats pid to 15050
2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_setup.py:_flush():67] Loading settings from /home/w2sg-arnav/.config/wandb/settings
2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_setup.py:_flush():67] Loading settings from /home/w2sg-arnav/cotton-disease/notebooks/wandb/settings
2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/run-20250304_094758-mgkyjsue/logs/debug.log
2025-03-04 09:47:58,519 INFO    MainThread:15050 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/run-20250304_094758-mgkyjsue/logs/debug-internal.log
2025-03-04 09:47:58,520 INFO    MainThread:15050 [wandb_init.py:monkeypatch_ipython():599] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7e74f0e48280>
2025-03-04 09:47:58,520 INFO    MainThread:15050 [wandb_init.py:init():761] calling init triggers
2025-03-04 09:47:58,520 INFO    MainThread:15050 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-04 09:47:58,520 INFO    MainThread:15050 [wandb_init.py:init():784] starting backend
2025-03-04 09:47:58,520 INFO    MainThread:15050 [wandb_init.py:init():788] sending inform_init request
2025-03-04 09:47:58,524 INFO    MainThread:15050 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-04 09:47:58,525 INFO    MainThread:15050 [wandb_init.py:init():803] backend started and connected
2025-03-04 09:47:58,538 INFO    MainThread:15050 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-04 09:47:58,539 INFO    MainThread:15050 [wandb_init.py:init():896] updated telemetry
2025-03-04 09:47:58,569 INFO    MainThread:15050 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 09:47:58,962 ERROR   MainThread:15050 [wandb_init.py:init():1481] error in wandb.init()
Traceback (most recent call last):
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1471, in init
    return wi.init(run_settings, run_config)
  File "/home/w2sg-arnav/anaconda3/envs/cotton_env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 968, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 403 Forbidden: {"errors":[{"message":"permission denied","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
2025-03-04 09:48:06,578 INFO    MainThread:15050 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/offline-run-20250304_094806-tthqfzj2/logs/debug.log
2025-03-04 09:48:06,578 INFO    MainThread:15050 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/offline-run-20250304_094806-tthqfzj2/logs/debug-internal.log
2025-03-04 09:48:06,578 INFO    MainThread:15050 [wandb_init.py:init():761] calling init triggers
2025-03-04 09:48:06,578 INFO    MainThread:15050 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-04 09:48:06,578 INFO    MainThread:15050 [wandb_init.py:init():784] starting backend
2025-03-04 09:48:06,578 INFO    MainThread:15050 [wandb_init.py:init():788] sending inform_init request
2025-03-04 09:48:06,579 INFO    MainThread:15050 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-03-04 09:48:06,580 INFO    MainThread:15050 [wandb_init.py:init():803] backend started and connected
2025-03-04 09:48:06,587 INFO    MainThread:15050 [wandb_run.py:_label_probe_notebook():1204] probe notebook
2025-03-04 09:48:06,588 INFO    MainThread:15050 [wandb_init.py:init():896] updated telemetry
2025-03-04 09:48:06,624 INFO    MainThread:15050 [wandb_init.py:init():920] communicating run to backend with 90.0 second timeout
2025-03-04 09:48:06,692 INFO    MainThread:15050 [wandb_init.py:init():995] starting run threads in backend
2025-03-04 09:48:06,817 INFO    MainThread:15050 [wandb_run.py:_console_start():2377] atexit reg
2025-03-04 09:48:06,817 INFO    MainThread:15050 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-03-04 09:48:06,817 INFO    MainThread:15050 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-03-04 09:48:06,817 INFO    MainThread:15050 [wandb_run.py:_redirect():2317] Redirects installed.
2025-03-04 09:48:06,818 INFO    MainThread:15050 [wandb_init.py:init():1037] run started, returning control to user process
2025-03-04 09:49:25,649 INFO    MainThread:15050 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/offline-run-20250304_094925-ehx3vu71/logs/debug.log
2025-03-04 09:49:25,649 INFO    MainThread:15050 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/w2sg-arnav/cotton-disease/notebooks/wandb/offline-run-20250304_094925-ehx3vu71/logs/debug-internal.log
2025-03-04 09:49:25,649 INFO    MainThread:15050 [wandb_init.py:init():761] calling init triggers
2025-03-04 09:49:25,649 INFO    MainThread:15050 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-03-04 09:49:25,649 INFO    MainThread:15050 [wandb_init.py:init():776] wandb.init() called while a run is active
